# Generated by Django 5.2.5 on 2025-09-08 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Número de celular')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('profile_type', models.CharField(choices=[('VISITOR', 'Visitante'), ('STUDENT', 'Estudiante'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional'), ('GROUP_REPRESENTATIVE', 'Representante de Grupo')], max_length=30, verbose_name='Tipo de Perfil')),
                ('is_unab_student', models.BooleanField(blank=True, null=True, verbose_name='¿Perteneces a la UNaB?')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución (estudio o trabajo)')),
                ('career', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrera que cursas')),
                ('year_of_study', models.IntegerField(blank=True, null=True, verbose_name='Año que cursas')),
                ('career_taught', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrera que dictas')),
                ('work_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de trabajo')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Empresa')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la institución o grupo')),
                ('group_municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partido al que pertenece la institución')),
                ('group_size', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de personas en el grupo')),
                ('asistencia_confirmada', models.BooleanField(default=False, verbose_name='Asistencia Confirmada')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la empresa o institución')),
                ('nombre_contacto', models.CharField(max_length=255, verbose_name='Nombre completo de la persona de contacto')),
                ('email_contacto', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico de la persona de contacto')),
                ('celular_contacto', models.CharField(max_length=20, verbose_name='Número de celular de contacto')),
                ('cargo_contacto', models.CharField(max_length=255, verbose_name='Cargo que cumple en la empresa / institución')),
                ('participacion_opciones', models.JSONField(default=list, verbose_name='¿Cómo les gustaría participar?')),
                ('participacion_otra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra forma de participación')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certificado', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('DISERTANTE', 'Disertante'), ('EMPRESA', 'Empresa')], max_length=10, verbose_name='Tipo de Certificado')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='PDF Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Disertante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('foto_url', models.CharField(blank=True, max_length=300, verbose_name='URL de la Foto')),
                ('tema_presentacion', models.CharField(max_length=255, verbose_name='Título de la Presentación')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_grupo', to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('dia', models.DateField(verbose_name='Día del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('aula', models.CharField(choices=[('Aula Magna', 'Aula Magna'), ('Aula 1', 'Aula 1'), ('Aula 2', 'Aula 2'), ('Aula 3', 'Aula 3'), ('Aula 4', 'Aula 4'), ('Aula 5', 'Aula 5'), ('Aula 6', 'Aula 6'), ('Aula 7', 'Aula 7'), ('Aula 8', 'Aula 8'), ('Aula 9', 'Aula 9'), ('Aula 10', 'Aula 10')], max_length=30, verbose_name='Aula')),
                ('disertante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disertante', verbose_name='Disertante')),
            ],
        ),
    ]
