# Generated by Django 5.2.5 on 2025-09-13 13:05

from django.db import migrations, models


def assign_categories_to_existing_programs(apps, schema_editor):
    """
    Asignar categorías diversas a los programas existentes basándose en las aulas
    para crear un dataset más rico y realista
    """
    Programa = apps.get_model('api', 'Programa')
    
    # Mapeo de aulas a categorías para diversificar el contenido
    aula_categoria_map = {
        'Aula Magna': ['LOGÍSTICA', 'NETWORKING', 'GESTIÓN'],
        'Aula 1': ['TRANSPORTE', 'SOSTENIBILIDAD', 'INNOVACIÓN'],
        'Aula 2': ['SUPPLY CHAIN', 'TECNOLOGÍA', 'GESTIÓN'],
        'Aula 3': ['TECNOLOGÍA', 'INNOVACIÓN', 'LOGÍSTICA'],
        'Aula 4': ['SOSTENIBILIDAD', 'GESTIÓN', 'NETWORKING'],
        'Aula 5': ['INNOVACIÓN', 'TECNOLOGÍA', 'SUPPLY CHAIN'],
        'Aula 6': ['GESTIÓN', 'TRANSPORTE', 'LOGÍSTICA'],
    }
    
    # Asignar categorías de forma cíclica por aula
    for aula, categorias in aula_categoria_map.items():
        programas_aula = Programa.objects.filter(aula=aula).order_by('hora_inicio')
        for i, programa in enumerate(programas_aula):
            categoria_idx = i % len(categorias)
            programa.categoria = categorias[categoria_idx]
            programa.save()


def reverse_assign_categories(apps, schema_editor):
    """
    Revertir la asignación de categorías, volviendo todo a LOGÍSTICA
    """
    Programa = apps.get_model('api', 'Programa')
    Programa.objects.all().update(categoria='LOGÍSTICA')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[('LOGÍSTICA', 'Logística'), ('TRANSPORTE', 'Transporte'), ('SUPPLY CHAIN', 'Supply Chain'), ('TECNOLOGÍA', 'Tecnología'), ('SOSTENIBILIDAD', 'Sostenibilidad'), ('INNOVACIÓN', 'Innovación'), ('GESTIÓN', 'Gestión'), ('NETWORKING', 'Networking')], default='LOGÍSTICA', max_length=20, verbose_name='Categoría'),
        ),
        migrations.RunPython(assign_categories_to_existing_programs, reverse_assign_categories),
    ]
