# Generated by Django 5.2.5 on 2025-09-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_categoria_to_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo de la empresa'),
        ),
    ]
