# Generated by Django 5.2.5 on 2025-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CUIT de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email corporativo de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la empresa'),
        ),
    ]
